using System;
using System.Collections.Generic;

namespace ZY.EFCore.Entities
{
    public partial class CrmOrder
    {
        public Guid CId { get; set; }
        public string CCode { get; set; }
        public Guid? CClientId { get; set; }
        public Guid? CDeputyDeptId { get; set; }
        public Guid? CClientInterCourseId { get; set; }
        public Guid? CMediaId { get; set; }
        public Guid? CStoreId { get; set; }
        public Guid? CBill { get; set; }
        public string COperateSkillCode { get; set; }
        public Guid? CBillDept { get; set; }
        public int? CStatus { get; set; }
        public DateTime? CPostTime { get; set; }
        public Guid? CAudit { get; set; }
        public DateTime? CAuditTime { get; set; }
        public string CAuditDesc { get; set; }
        public int? CIsCallTel { get; set; }
        public Guid? CDeputy { get; set; }
        public int? CType { get; set; }
        public int? CBuyMode { get; set; }
        public int? CPaymentMode { get; set; }
        public int? CSendMode { get; set; }
        public decimal? CMarketSum { get; set; }
        public decimal? CCommSum { get; set; }
        public decimal? COtherSum { get; set; }
        public decimal? CPreferentialPrice { get; set; }
        public decimal? CSendMoney { get; set; }
        public decimal? CDiscount { get; set; }
        public decimal? CReceivableMoney { get; set; }
        public decimal? CFactMoney { get; set; }
        public int? CBeforeLevel { get; set; }
        public int? CAfterLevel { get; set; }
        public decimal? CBeforeMoney { get; set; }
        public decimal? CAfterMoney { get; set; }
        public decimal? CBeforePoint { get; set; }
        public decimal? CUsedPoint { get; set; }
        public decimal? CSendPoint { get; set; }
        public decimal? CAfterPoint { get; set; }
        public decimal? CBeforeVolume { get; set; }
        public decimal? CUsedVolume { get; set; }
        public decimal? CSendVolume { get; set; }
        public decimal? CAfterVolume { get; set; }
        public decimal? CBeforeRedPacket { get; set; }
        public decimal? CUsedRedPacket { get; set; }
        public decimal? CSendRedPacket { get; set; }
        public decimal? CAfterRedPacket { get; set; }
        public decimal? CBeforeIncrement { get; set; }
        public decimal? CUsedIncrement { get; set; }
        public decimal? CAfterIncrement { get; set; }
        public decimal? CSendIncrement { get; set; }
        public int? CIsReceive { get; set; }
        public Guid? CClientAddress { get; set; }
        public Guid? CRegion { get; set; }
        public string CSendTel { get; set; }
        public DateTime? CSendTime { get; set; }
        public string CAddressee { get; set; }
        public string CAddress { get; set; }
        public string CZipCode { get; set; }
        public string CDescription { get; set; }
        public string COrderDesc { get; set; }
        public int? CIsReceipt { get; set; }
        public string CReceiptTitle { get; set; }
        public string CReceiptDesc { get; set; }
        public int? CIsExam { get; set; }
        public string CExamReason { get; set; }
        public Guid? CLead { get; set; }
        public DateTime? CExamTime { get; set; }
        public Guid? CFlowId { get; set; }
        public int? CIsPart { get; set; }
        public int? CIsOtherIncrept { get; set; }
        public int? CIsInsteard { get; set; }
        public int? CIsOwe { get; set; }
        public int? CIsSend { get; set; }
        public int? CIsCancel { get; set; }
        public Guid? CSendDept { get; set; }
        public Guid? CDistribute { get; set; }
        public Guid? CSingler { get; set; }
        public DateTime? CSingleTime { get; set; }
        public int? CExpress { get; set; }
        public int? CIsSelfUse { get; set; }
        public int? CIsOosSend { get; set; }
        public int? CIsSplit { get; set; }
        public int? CIsSplitDone { get; set; }
        public int? CIsPassExam { get; set; }
        public int? CIsException { get; set; }
        public decimal? CSendDiscount { get; set; }
        public decimal? COtherDiscount { get; set; }
        public decimal? CUseCardNum { get; set; }
        public decimal? CBeforeCardNum { get; set; }
        public decimal? CCardNum { get; set; }
        public decimal? CAfterCardNum { get; set; }
        public Guid? CLockedPeople { get; set; }
        public DateTime? CLockedTime { get; set; }
        public long? CCrmId { get; set; }
        public Guid? CCreator { get; set; }
        public DateTime? CCreateTime { get; set; }
        public Guid? CModifier { get; set; }
        public DateTime? CModifyTime { get; set; }
        public Guid? CCompanyId { get; set; }
        public int? CIsDelete { get; set; }
        public int? CIsPurchase { get; set; }
        public decimal? CApprovalMoney { get; set; }
        public decimal? CApprovalPostage { get; set; }
        public decimal? CApprovalPoint { get; set; }
        public decimal? CApprovalVolume { get; set; }
        public decimal? CApprovalRedPacket { get; set; }
        public int? CSource { get; set; }
        public Guid? CBaseOrderId { get; set; }
        public Guid? CSubCenterId { get; set; }
        public int? CIsSplitOrder { get; set; }
        public decimal? CApprovalAmount { get; set; }
        public int? CUnJdSubcenter { get; set; }
    }
}
